server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cabinssolitude
    username: cabinssolitude
    password: cabinssolitude2018
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true


